# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c0bcde2090899f3759523b39486311d"
application_url = "https://shopify-plugin-uikg.onrender.com"
embedded = true
name = "tokenproof-plugin"
handle = "tokenproof-plugin"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_products, write_products, read_inventory, read_themes, write_themes, read_inventory"

[auth]
redirect_urls = [
  "https://shopify-plugin-uikg.onrender.com/auth/callback",
  "https://shopify-plugin-uikg.onrender.com/auth/shopify/callback",
  "https://shopify-plugin-uikg.onrender.com/api/auth/callback"
]

[pos]
embedded = false
